#!/usr/bin/env bash
# testenv/provision.sh
#
# Stand up a SINGLE-INSTANCE Nagios test environment for the nagioscheckreceiver
# end-to-end test. Everything lives on one host so it works in CI (no inter-node
# networking): Nagios Core 4 + Apache/CGI (API mode), perfdata files (File mode),
# and a source-built MK Livestatus socket (Livestatus mode), with local workloads
# (nginx, postgres, stress-ng) so all three modes carry real, varied data.
#
# Target: Debian 12 / Ubuntu 24.04 (apt-based). Must run as root. Re-runnable.
#
# Env knobs (all optional):
#   NAGIOS_ADMIN_PASS  basic-auth password for the CGI/API user (default: nagiosci)
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive

NAGIOS_ADMIN_USER=nagiosadmin
NAGIOS_ADMIN_PASS="${NAGIOS_ADMIN_PASS:-nagiosci}"

NAGIOS_ETC=/etc/nagios4
NAGIOS_VAR=/var/lib/nagios4
LIVESTATUS_SOCKET="${NAGIOS_VAR}/rw/live"
LIVESTATUS_SRC=/opt/livestatus
PLUGINS=/usr/lib/nagios/plugins
SENTINEL=/var/lib/nagios-testenv.provisioned

# --------------------------------------------------------------------------
# 1. Packages
# --------------------------------------------------------------------------
apt-get update
apt-get install -y \
  nagios4 nagios-nrpe-server nagios-nrpe-plugin \
  monitoring-plugins monitoring-plugins-contrib \
  apache2 apache2-utils nginx stress-ng \
  build-essential autoconf automake libtool pkg-config gcc g++ make git wget curl

a2enmod cgi authn_core auth_basic authz_core >/dev/null 2>&1 || true

# --------------------------------------------------------------------------
# 2. Small swap so check_swap reports real data
# --------------------------------------------------------------------------
if [ ! -f /swapfile ]; then
  fallocate -l 512M /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# --------------------------------------------------------------------------
# 3. nginx on :8080 (Apache owns :80 for the Nagios CGIs) -> check_http target
# --------------------------------------------------------------------------
sed -i 's/listen 80 default_server;/listen 8080 default_server;/; s/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/' \
  /etc/nginx/sites-available/default
echo "nagios test env OK $(hostname)" > /var/www/html/index.nginx-debian.html
systemctl enable --now nginx
systemctl restart nginx

# --------------------------------------------------------------------------
# 4. NRPE daemon (localhost only) with tripping thresholds
# --------------------------------------------------------------------------
cat > /etc/nagios/nrpe_local.cfg <<EOF
allowed_hosts=127.0.0.1,::1
command[check_load]=${PLUGINS}/check_load -w 1.5,1.4,1.3 -c 2.5,2.2,2.0
command[check_users]=${PLUGINS}/check_users -w 5 -c 10
command[check_disk_root]=${PLUGINS}/check_disk -w 20% -c 10% -p /
command[check_procs]=${PLUGINS}/check_procs -w 220 -c 300
command[check_swap]=${PLUGINS}/check_swap -w 40% -c 20%
command[check_zombie]=${PLUGINS}/check_procs -w 5 -c 10 -s Z
EOF
sed -i 's/^server_address=.*/server_address=127.0.0.1/' /etc/nagios/nrpe.cfg || true
systemctl enable --now nagios-nrpe-server
systemctl restart nagios-nrpe-server

# --------------------------------------------------------------------------
# 6. Dynamic workload: busy/idle swings so checks move and perfdata looks live
# --------------------------------------------------------------------------
mkdir -p /opt/workload
cat > /opt/workload/workload.sh <<'WL'
#!/usr/bin/env bash
set -u
while true; do
  # busy phase (~90s): many short-lived procs + CPU/mem pressure
  for i in $(seq 1 180); do ( sleep 120 ) & done
  stress-ng --cpu 2 --vm 1 --vm-bytes 50% --timeout 90s || true
  pkill -f 'sleep 120' || true
  # idle phase (~90s)
  sleep 90
done
WL
chmod +x /opt/workload/workload.sh
cat > /etc/systemd/system/workload.service <<'UNIT'
[Unit]
Description=Dynamic Nagios test workload (stress swings)
After=network.target
[Service]
ExecStart=/opt/workload/workload.sh
Restart=always
Nice=10
[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable --now workload.service

# --------------------------------------------------------------------------
# 7. Build MK Livestatus (ageric fork, Nagios-4 compatible) from source
#    Needs Nagios Core source headers, generated by ./configure of the
#    matching Nagios source tree (produces include/locations.h etc.).
# --------------------------------------------------------------------------
NAGVER="$(dpkg-query -W -f='${Version}' nagios4 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
NAG_SRC="/opt/nagioscore-nagios-${NAGVER}"
if [ ! -d "${NAG_SRC}" ]; then
  cd /opt
  wget -q "https://github.com/NagiosEnterprises/nagioscore/archive/refs/tags/nagios-${NAGVER}.tar.gz" -O "nagios-${NAGVER}.tar.gz"
  tar xzf "nagios-${NAGVER}.tar.gz"
  cd "${NAG_SRC}"
  ./configure >/tmp/nagios-src-configure.log 2>&1
fi

# livestatus #includes the Nagios headers as <nagios/...>, but the Nagios source
# tree exposes them at the top level of include/. Expose that dir under a
# 'nagios/' subdir on the include path so both <nagios.h> and <nagios/objects.h>
# resolve.
mkdir -p /opt/nagios-includes
ln -sfn "${NAG_SRC}/include" /opt/nagios-includes/nagios

if [ ! -f "${LIVESTATUS_SRC}/src/livestatus.o" ]; then
  rm -rf "${LIVESTATUS_SRC}"
  git clone https://github.com/ageric/livestatus.git "${LIVESTATUS_SRC}"
  cd "${LIVESTATUS_SRC}"
  autoreconf -i >/tmp/ls-autoreconf.log 2>&1 || { aclocal; automake --add-missing --copy; autoconf; }
  # Build flags for modern toolchains (gcc 13/14 on Ubuntu 24.04):
  #   -I.../nagios + source root : resolve <nagios/...> and "lib/libnagios.h"
  #   -include pthread.h         : pthread_mutex_* decls (newer glibc dropped the
  #                                transitive include older Debian provided)
  #   -fcommon                   : merge tentative defs (gcc 10+ defaults to
  #                                -fno-common -> g_mainthread_id multiple-def)
  ./configure CPPFLAGS="-I/opt/nagios-includes -I${NAG_SRC}/include -I${NAG_SRC} -include pthread.h -fcommon" >/tmp/ls-configure.log 2>&1
  make >/tmp/ls-make.log 2>&1
fi
test -f "${LIVESTATUS_SRC}/src/livestatus.o"

# --------------------------------------------------------------------------
# 8. Nagios object config: localhost host + services across the three modes
# --------------------------------------------------------------------------
# remove any stale artifact from earlier script versions (keeps re-runs clean)
rm -f "${NAGIOS_ETC}/conf.d/ci-perfdata-commands.cfg"

cat > "${NAGIOS_ETC}/conf.d/ci-localhost.cfg" <<EOF
# Single 'nagios-testenv' host monitored via stock local plugins at a fast
# cadence so all three ingestion modes carry fresh data quickly. The dynamic
# workload (stress-ng) drives load/procs/swap to swing OK<->WARNING<->CRITICAL.
define command {
    command_name  ci_check_http_8080
    command_line  ${PLUGINS}/check_http -H 127.0.0.1 -p 8080
}

define host {
    use                 linux-server
    host_name           nagios-testenv
    alias               nagios test env (single instance)
    address             127.0.0.1
    max_check_attempts  3
    check_interval      1
    retry_interval      1
}

define service {
    use                 local-service
    host_name           nagios-testenv
    service_description Current Load
    check_command       check_local_load!5.0,4.0,3.0!10.0,6.0,4.0
    check_interval      1
    retry_interval      1
}
define service {
    use                 local-service
    host_name           nagios-testenv
    service_description Current Users
    check_command       check_local_users!20!50
    check_interval      1
    retry_interval      1
}
define service {
    use                 local-service
    host_name           nagios-testenv
    service_description Root Partition
    check_command       check_local_disk!20%!10%!/
    check_interval      1
    retry_interval      1
}
define service {
    use                 local-service
    host_name           nagios-testenv
    service_description Total Processes
    check_command       check_local_procs!250!400!RSZDT
    check_interval      1
    retry_interval      1
}
define service {
    use                 local-service
    host_name           nagios-testenv
    service_description Swap Usage
    check_command       check_local_swap!20%!10%
    check_interval      1
    retry_interval      1
}
define service {
    use                 local-service
    host_name           nagios-testenv
    service_description PING
    check_command       check_ping!100.0,20%!500.0,60%
    check_interval      1
    retry_interval      1
}
define service {
    use                 local-service
    host_name           nagios-testenv
    service_description HTTP
    check_command       ci_check_http_8080
    check_interval      1
    retry_interval      1
}
EOF

# --------------------------------------------------------------------------
# 9. nagios.cfg: enable perfdata files (File mode) + load livestatus broker
# --------------------------------------------------------------------------
NAGCFG="${NAGIOS_ETC}/nagios.cfg"
# strip any prior testenv block so re-runs stay idempotent
sed -i '/# >>> nagios-testenv >>>/,/# <<< nagios-testenv <<</d' "${NAGCFG}"
cat >> "${NAGCFG}" <<EOF
# >>> nagios-testenv >>>
process_performance_data=1
service_perfdata_file=${NAGIOS_VAR}/service-perfdata
service_perfdata_file_template=[SERVICEPERFDATA]\t\$TIMET\$\t\$HOSTNAME\$\t\$SERVICEDESC\$\t\$SERVICESTATE\$\t\$SERVICEOUTPUT\$\t\$SERVICEPERFDATA\$
service_perfdata_file_mode=a
host_perfdata_file=${NAGIOS_VAR}/host-perfdata
host_perfdata_file_template=[HOSTPERFDATA]\t\$TIMET\$\t\$HOSTNAME\$\t\$HOSTSTATE\$\t\$HOSTOUTPUT\$\t\$HOSTPERFDATA\$
host_perfdata_file_mode=a
broker_module=${LIVESTATUS_SRC}/src/livestatus.o ${LIVESTATUS_SOCKET}
# <<< nagios-testenv <<<
EOF

# rw dir for the livestatus socket; tmpfiles rule recreates it on boot
mkdir -p "${NAGIOS_VAR}/rw"
chown nagios:nagios "${NAGIOS_VAR}/rw"
echo "d ${NAGIOS_VAR}/rw 2710 nagios nagios -" > /etc/tmpfiles.d/nagios-testenv.conf

# --------------------------------------------------------------------------
# 10. Apache/CGI basic auth user for API mode (statusjson.cgi)
# --------------------------------------------------------------------------
htpasswd -bc "${NAGIOS_ETC}/htpasswd.users" "${NAGIOS_ADMIN_USER}" "${NAGIOS_ADMIN_PASS}"

# --------------------------------------------------------------------------
# 11. (Re)start everything
# --------------------------------------------------------------------------
systemctl enable apache2
systemctl restart apache2
# validate config before (re)starting nagios
/usr/sbin/nagios4 -v "${NAGCFG}"
systemctl enable nagios4
systemctl restart nagios4

touch "${SENTINEL}"
echo "PROVISION COMPLETE"
