// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nagioscheck")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nagioscheckreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
