// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNagiosCheckExecutionTimeDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordNagiosCheckLastCheckDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordNagiosCheckLatencyDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNagiosCheckStateDataPoint(ts, 1, AttributeNagiosStateOk)

			allMetricsCount++
			mb.RecordNagiosPerfdataCriticalDataPoint(ts, 1, "nagios.perfdata.label-val", "nagios.perfdata.unit-val")

			allMetricsCount++
			mb.RecordNagiosPerfdataMaxDataPoint(ts, 1, "nagios.perfdata.label-val", "nagios.perfdata.unit-val")

			allMetricsCount++
			mb.RecordNagiosPerfdataMinDataPoint(ts, 1, "nagios.perfdata.label-val", "nagios.perfdata.unit-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNagiosPerfdataValueDataPoint(ts, 1, "nagios.perfdata.label-val", "nagios.perfdata.unit-val")

			allMetricsCount++
			mb.RecordNagiosPerfdataWarningDataPoint(ts, 1, "nagios.perfdata.label-val", "nagios.perfdata.unit-val")

			rb := mb.NewResourceBuilder()
			rb.SetNagiosCheckCommand("nagios.check.command-val")
			rb.SetNagiosHostName("nagios.host.name-val")
			rb.SetNagiosServiceDescription("nagios.service.description-val")
			rb.SetNagiosSource("nagios.source-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "nagios.check.execution_time":
					assert.False(t, validatedMetrics["nagios.check.execution_time"], "Found a duplicate in the metrics slice: nagios.check.execution_time")
					validatedMetrics["nagios.check.execution_time"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Check execution duration in seconds.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "nagios.check.last_check":
					assert.False(t, validatedMetrics["nagios.check.last_check"], "Found a duplicate in the metrics slice: nagios.check.last_check")
					validatedMetrics["nagios.check.last_check"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Unix timestamp of last check execution.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nagios.check.latency":
					assert.False(t, validatedMetrics["nagios.check.latency"], "Found a duplicate in the metrics slice: nagios.check.latency")
					validatedMetrics["nagios.check.latency"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Scheduling latency in seconds.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "nagios.check.state":
					assert.False(t, validatedMetrics["nagios.check.state"], "Found a duplicate in the metrics slice: nagios.check.state")
					validatedMetrics["nagios.check.state"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Nagios check state as an integer: 0=OK, 1=WARNING, 2=CRITICAL, 3=UNKNOWN.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("nagios.state")
					assert.True(t, ok)
					assert.Equal(t, "ok", attrVal.Str())
				case "nagios.perfdata.critical":
					assert.False(t, validatedMetrics["nagios.perfdata.critical"], "Found a duplicate in the metrics slice: nagios.perfdata.critical")
					validatedMetrics["nagios.perfdata.critical"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Critical threshold upper bound from performance data.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("nagios.perfdata.label")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.label-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("nagios.perfdata.unit")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.unit-val", attrVal.Str())
				case "nagios.perfdata.max":
					assert.False(t, validatedMetrics["nagios.perfdata.max"], "Found a duplicate in the metrics slice: nagios.perfdata.max")
					validatedMetrics["nagios.perfdata.max"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum possible value from performance data.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("nagios.perfdata.label")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.label-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("nagios.perfdata.unit")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.unit-val", attrVal.Str())
				case "nagios.perfdata.min":
					assert.False(t, validatedMetrics["nagios.perfdata.min"], "Found a duplicate in the metrics slice: nagios.perfdata.min")
					validatedMetrics["nagios.perfdata.min"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Minimum possible value from performance data.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("nagios.perfdata.label")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.label-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("nagios.perfdata.unit")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.unit-val", attrVal.Str())
				case "nagios.perfdata.value":
					assert.False(t, validatedMetrics["nagios.perfdata.value"], "Found a duplicate in the metrics slice: nagios.perfdata.value")
					validatedMetrics["nagios.perfdata.value"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The performance data metric value from Nagios plugin output.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("nagios.perfdata.label")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.label-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("nagios.perfdata.unit")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.unit-val", attrVal.Str())
				case "nagios.perfdata.warning":
					assert.False(t, validatedMetrics["nagios.perfdata.warning"], "Found a duplicate in the metrics slice: nagios.perfdata.warning")
					validatedMetrics["nagios.perfdata.warning"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Warning threshold upper bound from performance data.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("nagios.perfdata.label")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.label-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("nagios.perfdata.unit")
					assert.True(t, ok)
					assert.Equal(t, "nagios.perfdata.unit-val", attrVal.Str())
				}
			}
		})
	}
}
