// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	conventions "go.opentelemetry.io/otel/semconv/v1.27.0"
)

// AttributeNagiosState specifies the value nagios.state attribute.
type AttributeNagiosState int

const (
	_ AttributeNagiosState = iota
	AttributeNagiosStateOk
	AttributeNagiosStateWarning
	AttributeNagiosStateCritical
	AttributeNagiosStateUnknown
)

// String returns the string representation of the AttributeNagiosState.
func (av AttributeNagiosState) String() string {
	switch av {
	case AttributeNagiosStateOk:
		return "ok"
	case AttributeNagiosStateWarning:
		return "warning"
	case AttributeNagiosStateCritical:
		return "critical"
	case AttributeNagiosStateUnknown:
		return "unknown"
	}
	return ""
}

// MapAttributeNagiosState is a helper map of string to AttributeNagiosState attribute value.
var MapAttributeNagiosState = map[string]AttributeNagiosState{
	"ok":       AttributeNagiosStateOk,
	"warning":  AttributeNagiosStateWarning,
	"critical": AttributeNagiosStateCritical,
	"unknown":  AttributeNagiosStateUnknown,
}

var MetricsInfo = metricsInfo{
	NagiosCheckExecutionTime: metricInfo{
		Name: "nagios.check.execution_time",
	},
	NagiosCheckLastCheck: metricInfo{
		Name: "nagios.check.last_check",
	},
	NagiosCheckLatency: metricInfo{
		Name: "nagios.check.latency",
	},
	NagiosCheckState: metricInfo{
		Name: "nagios.check.state",
	},
	NagiosPerfdataCritical: metricInfo{
		Name: "nagios.perfdata.critical",
	},
	NagiosPerfdataMax: metricInfo{
		Name: "nagios.perfdata.max",
	},
	NagiosPerfdataMin: metricInfo{
		Name: "nagios.perfdata.min",
	},
	NagiosPerfdataValue: metricInfo{
		Name: "nagios.perfdata.value",
	},
	NagiosPerfdataWarning: metricInfo{
		Name: "nagios.perfdata.warning",
	},
}

type metricsInfo struct {
	NagiosCheckExecutionTime metricInfo
	NagiosCheckLastCheck     metricInfo
	NagiosCheckLatency       metricInfo
	NagiosCheckState         metricInfo
	NagiosPerfdataCritical   metricInfo
	NagiosPerfdataMax        metricInfo
	NagiosPerfdataMin        metricInfo
	NagiosPerfdataValue      metricInfo
	NagiosPerfdataWarning    metricInfo
}

type metricInfo struct {
	Name string
}

type metricNagiosCheckExecutionTime struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.check.execution_time metric with initial data.
func (m *metricNagiosCheckExecutionTime) init() {
	m.data.SetName("nagios.check.execution_time")
	m.data.SetDescription("Check execution duration in seconds.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricNagiosCheckExecutionTime) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosCheckExecutionTime) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosCheckExecutionTime) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosCheckExecutionTime(cfg MetricConfig) metricNagiosCheckExecutionTime {
	m := metricNagiosCheckExecutionTime{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosCheckLastCheck struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.check.last_check metric with initial data.
func (m *metricNagiosCheckLastCheck) init() {
	m.data.SetName("nagios.check.last_check")
	m.data.SetDescription("Unix timestamp of last check execution.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricNagiosCheckLastCheck) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosCheckLastCheck) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosCheckLastCheck) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosCheckLastCheck(cfg MetricConfig) metricNagiosCheckLastCheck {
	m := metricNagiosCheckLastCheck{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosCheckLatency struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.check.latency metric with initial data.
func (m *metricNagiosCheckLatency) init() {
	m.data.SetName("nagios.check.latency")
	m.data.SetDescription("Scheduling latency in seconds.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricNagiosCheckLatency) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosCheckLatency) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosCheckLatency) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosCheckLatency(cfg MetricConfig) metricNagiosCheckLatency {
	m := metricNagiosCheckLatency{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosCheckState struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.check.state metric with initial data.
func (m *metricNagiosCheckState) init() {
	m.data.SetName("nagios.check.state")
	m.data.SetDescription("Nagios check state as an integer: 0=OK, 1=WARNING, 2=CRITICAL, 3=UNKNOWN.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNagiosCheckState) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, nagiosStateAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("nagios.state", nagiosStateAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosCheckState) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosCheckState) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosCheckState(cfg MetricConfig) metricNagiosCheckState {
	m := metricNagiosCheckState{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosPerfdataCritical struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.perfdata.critical metric with initial data.
func (m *metricNagiosPerfdataCritical) init() {
	m.data.SetName("nagios.perfdata.critical")
	m.data.SetDescription("Critical threshold upper bound from performance data.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNagiosPerfdataCritical) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("nagios.perfdata.label", nagiosPerfdataLabelAttributeValue)
	dp.Attributes().PutStr("nagios.perfdata.unit", nagiosPerfdataUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosPerfdataCritical) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosPerfdataCritical) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosPerfdataCritical(cfg MetricConfig) metricNagiosPerfdataCritical {
	m := metricNagiosPerfdataCritical{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosPerfdataMax struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.perfdata.max metric with initial data.
func (m *metricNagiosPerfdataMax) init() {
	m.data.SetName("nagios.perfdata.max")
	m.data.SetDescription("Maximum possible value from performance data.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNagiosPerfdataMax) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("nagios.perfdata.label", nagiosPerfdataLabelAttributeValue)
	dp.Attributes().PutStr("nagios.perfdata.unit", nagiosPerfdataUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosPerfdataMax) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosPerfdataMax) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosPerfdataMax(cfg MetricConfig) metricNagiosPerfdataMax {
	m := metricNagiosPerfdataMax{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosPerfdataMin struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.perfdata.min metric with initial data.
func (m *metricNagiosPerfdataMin) init() {
	m.data.SetName("nagios.perfdata.min")
	m.data.SetDescription("Minimum possible value from performance data.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNagiosPerfdataMin) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("nagios.perfdata.label", nagiosPerfdataLabelAttributeValue)
	dp.Attributes().PutStr("nagios.perfdata.unit", nagiosPerfdataUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosPerfdataMin) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosPerfdataMin) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosPerfdataMin(cfg MetricConfig) metricNagiosPerfdataMin {
	m := metricNagiosPerfdataMin{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosPerfdataValue struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.perfdata.value metric with initial data.
func (m *metricNagiosPerfdataValue) init() {
	m.data.SetName("nagios.perfdata.value")
	m.data.SetDescription("The performance data metric value from Nagios plugin output.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNagiosPerfdataValue) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("nagios.perfdata.label", nagiosPerfdataLabelAttributeValue)
	dp.Attributes().PutStr("nagios.perfdata.unit", nagiosPerfdataUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosPerfdataValue) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosPerfdataValue) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosPerfdataValue(cfg MetricConfig) metricNagiosPerfdataValue {
	m := metricNagiosPerfdataValue{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNagiosPerfdataWarning struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nagios.perfdata.warning metric with initial data.
func (m *metricNagiosPerfdataWarning) init() {
	m.data.SetName("nagios.perfdata.warning")
	m.data.SetDescription("Warning threshold upper bound from performance data.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNagiosPerfdataWarning) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("nagios.perfdata.label", nagiosPerfdataLabelAttributeValue)
	dp.Attributes().PutStr("nagios.perfdata.unit", nagiosPerfdataUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNagiosPerfdataWarning) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNagiosPerfdataWarning) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNagiosPerfdataWarning(cfg MetricConfig) metricNagiosPerfdataWarning {
	m := metricNagiosPerfdataWarning{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricNagiosCheckExecutionTime metricNagiosCheckExecutionTime
	metricNagiosCheckLastCheck     metricNagiosCheckLastCheck
	metricNagiosCheckLatency       metricNagiosCheckLatency
	metricNagiosCheckState         metricNagiosCheckState
	metricNagiosPerfdataCritical   metricNagiosPerfdataCritical
	metricNagiosPerfdataMax        metricNagiosPerfdataMax
	metricNagiosPerfdataMin        metricNagiosPerfdataMin
	metricNagiosPerfdataValue      metricNagiosPerfdataValue
	metricNagiosPerfdataWarning    metricNagiosPerfdataWarning
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricNagiosCheckExecutionTime: newMetricNagiosCheckExecutionTime(mbc.Metrics.NagiosCheckExecutionTime),
		metricNagiosCheckLastCheck:     newMetricNagiosCheckLastCheck(mbc.Metrics.NagiosCheckLastCheck),
		metricNagiosCheckLatency:       newMetricNagiosCheckLatency(mbc.Metrics.NagiosCheckLatency),
		metricNagiosCheckState:         newMetricNagiosCheckState(mbc.Metrics.NagiosCheckState),
		metricNagiosPerfdataCritical:   newMetricNagiosPerfdataCritical(mbc.Metrics.NagiosPerfdataCritical),
		metricNagiosPerfdataMax:        newMetricNagiosPerfdataMax(mbc.Metrics.NagiosPerfdataMax),
		metricNagiosPerfdataMin:        newMetricNagiosPerfdataMin(mbc.Metrics.NagiosPerfdataMin),
		metricNagiosPerfdataValue:      newMetricNagiosPerfdataValue(mbc.Metrics.NagiosPerfdataValue),
		metricNagiosPerfdataWarning:    newMetricNagiosPerfdataWarning(mbc.Metrics.NagiosPerfdataWarning),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.NagiosCheckCommand.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["nagios.check.command"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosCheckCommand.MetricsInclude)
	}
	if mbc.ResourceAttributes.NagiosCheckCommand.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["nagios.check.command"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosCheckCommand.MetricsExclude)
	}
	if mbc.ResourceAttributes.NagiosHostName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["nagios.host.name"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosHostName.MetricsInclude)
	}
	if mbc.ResourceAttributes.NagiosHostName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["nagios.host.name"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosHostName.MetricsExclude)
	}
	if mbc.ResourceAttributes.NagiosServiceDescription.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["nagios.service.description"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosServiceDescription.MetricsInclude)
	}
	if mbc.ResourceAttributes.NagiosServiceDescription.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["nagios.service.description"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosServiceDescription.MetricsExclude)
	}
	if mbc.ResourceAttributes.NagiosSource.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["nagios.source"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosSource.MetricsInclude)
	}
	if mbc.ResourceAttributes.NagiosSource.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["nagios.source"] = filter.CreateFilter(mbc.ResourceAttributes.NagiosSource.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	rm.SetSchemaUrl(conventions.SchemaURL)
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNagiosCheckExecutionTime.emit(ils.Metrics())
	mb.metricNagiosCheckLastCheck.emit(ils.Metrics())
	mb.metricNagiosCheckLatency.emit(ils.Metrics())
	mb.metricNagiosCheckState.emit(ils.Metrics())
	mb.metricNagiosPerfdataCritical.emit(ils.Metrics())
	mb.metricNagiosPerfdataMax.emit(ils.Metrics())
	mb.metricNagiosPerfdataMin.emit(ils.Metrics())
	mb.metricNagiosPerfdataValue.emit(ils.Metrics())
	mb.metricNagiosPerfdataWarning.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNagiosCheckExecutionTimeDataPoint adds a data point to nagios.check.execution_time metric.
func (mb *MetricsBuilder) RecordNagiosCheckExecutionTimeDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricNagiosCheckExecutionTime.recordDataPoint(mb.startTime, ts, val)
}

// RecordNagiosCheckLastCheckDataPoint adds a data point to nagios.check.last_check metric.
func (mb *MetricsBuilder) RecordNagiosCheckLastCheckDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNagiosCheckLastCheck.recordDataPoint(mb.startTime, ts, val)
}

// RecordNagiosCheckLatencyDataPoint adds a data point to nagios.check.latency metric.
func (mb *MetricsBuilder) RecordNagiosCheckLatencyDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricNagiosCheckLatency.recordDataPoint(mb.startTime, ts, val)
}

// RecordNagiosCheckStateDataPoint adds a data point to nagios.check.state metric.
func (mb *MetricsBuilder) RecordNagiosCheckStateDataPoint(ts pcommon.Timestamp, val int64, nagiosStateAttributeValue AttributeNagiosState) {
	mb.metricNagiosCheckState.recordDataPoint(mb.startTime, ts, val, nagiosStateAttributeValue.String())
}

// RecordNagiosPerfdataCriticalDataPoint adds a data point to nagios.perfdata.critical metric.
func (mb *MetricsBuilder) RecordNagiosPerfdataCriticalDataPoint(ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	mb.metricNagiosPerfdataCritical.recordDataPoint(mb.startTime, ts, val, nagiosPerfdataLabelAttributeValue, nagiosPerfdataUnitAttributeValue)
}

// RecordNagiosPerfdataMaxDataPoint adds a data point to nagios.perfdata.max metric.
func (mb *MetricsBuilder) RecordNagiosPerfdataMaxDataPoint(ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	mb.metricNagiosPerfdataMax.recordDataPoint(mb.startTime, ts, val, nagiosPerfdataLabelAttributeValue, nagiosPerfdataUnitAttributeValue)
}

// RecordNagiosPerfdataMinDataPoint adds a data point to nagios.perfdata.min metric.
func (mb *MetricsBuilder) RecordNagiosPerfdataMinDataPoint(ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	mb.metricNagiosPerfdataMin.recordDataPoint(mb.startTime, ts, val, nagiosPerfdataLabelAttributeValue, nagiosPerfdataUnitAttributeValue)
}

// RecordNagiosPerfdataValueDataPoint adds a data point to nagios.perfdata.value metric.
func (mb *MetricsBuilder) RecordNagiosPerfdataValueDataPoint(ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	mb.metricNagiosPerfdataValue.recordDataPoint(mb.startTime, ts, val, nagiosPerfdataLabelAttributeValue, nagiosPerfdataUnitAttributeValue)
}

// RecordNagiosPerfdataWarningDataPoint adds a data point to nagios.perfdata.warning metric.
func (mb *MetricsBuilder) RecordNagiosPerfdataWarningDataPoint(ts pcommon.Timestamp, val float64, nagiosPerfdataLabelAttributeValue string, nagiosPerfdataUnitAttributeValue string) {
	mb.metricNagiosPerfdataWarning.recordDataPoint(mb.startTime, ts, val, nagiosPerfdataLabelAttributeValue, nagiosPerfdataUnitAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
