// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetNagiosCheckCommand sets provided value as "nagios.check.command" attribute.
func (rb *ResourceBuilder) SetNagiosCheckCommand(val string) {
	if rb.config.NagiosCheckCommand.Enabled {
		rb.res.Attributes().PutStr("nagios.check.command", val)
	}
}

// SetNagiosHostName sets provided value as "nagios.host.name" attribute.
func (rb *ResourceBuilder) SetNagiosHostName(val string) {
	if rb.config.NagiosHostName.Enabled {
		rb.res.Attributes().PutStr("nagios.host.name", val)
	}
}

// SetNagiosServiceDescription sets provided value as "nagios.service.description" attribute.
func (rb *ResourceBuilder) SetNagiosServiceDescription(val string) {
	if rb.config.NagiosServiceDescription.Enabled {
		rb.res.Attributes().PutStr("nagios.service.description", val)
	}
}

// SetNagiosSource sets provided value as "nagios.source" attribute.
func (rb *ResourceBuilder) SetNagiosSource(val string) {
	if rb.config.NagiosSource.Enabled {
		rb.res.Attributes().PutStr("nagios.source", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
