// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetNagiosCheckCommand("nagios.check.command-val")
			rb.SetNagiosHostName("nagios.host.name-val")
			rb.SetNagiosServiceDescription("nagios.service.description-val")
			rb.SetNagiosSource("nagios.source-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 4, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 4, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("nagios.check.command")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nagios.check.command-val", val.Str())
			}
			val, ok = res.Attributes().Get("nagios.host.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nagios.host.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("nagios.service.description")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nagios.service.description-val", val.Str())
			}
			val, ok = res.Attributes().Get("nagios.source")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nagios.source-val", val.Str())
			}
		})
	}
}
