// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for nagioscheck metrics.
type MetricsConfig struct {
	NagiosCheckExecutionTime MetricConfig `mapstructure:"nagios.check.execution_time"`
	NagiosCheckLastCheck     MetricConfig `mapstructure:"nagios.check.last_check"`
	NagiosCheckLatency       MetricConfig `mapstructure:"nagios.check.latency"`
	NagiosCheckState         MetricConfig `mapstructure:"nagios.check.state"`
	NagiosPerfdataCritical   MetricConfig `mapstructure:"nagios.perfdata.critical"`
	NagiosPerfdataMax        MetricConfig `mapstructure:"nagios.perfdata.max"`
	NagiosPerfdataMin        MetricConfig `mapstructure:"nagios.perfdata.min"`
	NagiosPerfdataValue      MetricConfig `mapstructure:"nagios.perfdata.value"`
	NagiosPerfdataWarning    MetricConfig `mapstructure:"nagios.perfdata.warning"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NagiosCheckExecutionTime: MetricConfig{
			Enabled: true,
		},
		NagiosCheckLastCheck: MetricConfig{
			Enabled: false,
		},
		NagiosCheckLatency: MetricConfig{
			Enabled: false,
		},
		NagiosCheckState: MetricConfig{
			Enabled: true,
		},
		NagiosPerfdataCritical: MetricConfig{
			Enabled: false,
		},
		NagiosPerfdataMax: MetricConfig{
			Enabled: false,
		},
		NagiosPerfdataMin: MetricConfig{
			Enabled: false,
		},
		NagiosPerfdataValue: MetricConfig{
			Enabled: true,
		},
		NagiosPerfdataWarning: MetricConfig{
			Enabled: false,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for nagioscheck resource attributes.
type ResourceAttributesConfig struct {
	NagiosCheckCommand       ResourceAttributeConfig `mapstructure:"nagios.check.command"`
	NagiosHostName           ResourceAttributeConfig `mapstructure:"nagios.host.name"`
	NagiosServiceDescription ResourceAttributeConfig `mapstructure:"nagios.service.description"`
	NagiosSource             ResourceAttributeConfig `mapstructure:"nagios.source"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		NagiosCheckCommand: ResourceAttributeConfig{
			Enabled: true,
		},
		NagiosHostName: ResourceAttributeConfig{
			Enabled: true,
		},
		NagiosServiceDescription: ResourceAttributeConfig{
			Enabled: true,
		},
		NagiosSource: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for nagioscheck metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
